### ISSUE TITLE
feature: cut a new release

### ISSUE THREAD

**Issue by char0n** [tree-sitter-grammars/tree-sitter-yaml#15]
### Did you check the tree-sitter docs?

- [x] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser

### Is your feature request related to a problem? Please describe.

Hi, 

First off all, thank you for all the work on this grammar. There has been an issue related to limited line length reported in https://github.com/tree-sitter-grammars/tree-sitter-yaml/issues/6. The issue has already been resolved in the begging of May 2024. 

### Describe the solution you'd like

It would be great if the bug fix from https://github.com/tree-sitter-grammars/tree-sitter-yaml/issues/6 could be released in new patch release. Is there  something I can do to help with this effort?

**Comment by amaanq** [comment]
Hey, sorry for taking a while, I hadn't turned on watch all activity for this repo. I've updated the bindings and dependencies for each ecosystem, and published 0.7.0 🙂

**Comment by char0n** [comment]
Thank you!
